#!/bin/sh
case "$1" in
    start)
        echo "🚀 Levantando Z-Gate Core..."
        udhcpc -i eth0 -n -t 2 -q &
        ip link add dev wg0 type wireguard
        ip addr add 10.10.0.1/24 dev wg0
        ip link set mtu 1420 up dev wg0
        /usr/bin/z-gate-agent > /dev/console 2>&1 &
        ;;
esac
