#!/bin/sh
# Montar sistemas de archivos virtuales esenciales
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs devtmpfs /dev

echo "--------------------------------"
echo " Z-GATE BOOT SYSTEM: SUCCESS "
echo "--------------------------------"

# Pasar el control al sistema real (Busybox init)
exec /sbin/init